Subo Pre-Push

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,16 @@
 #!/bin/bash
 echo "Running ktlintFormat..."
+
 ./gradlew ktlintFormat
 
-if [ $? -ne 0 ]; then
-  echo "ktlintFormat failed. Please fix formatting issues before committing."
-  exit 1
-fi
+EXIT_CODE=$?
 
-echo "Formatting complete. Proceeding with commit."
+if [ $EXIT_CODE -ne 0 ]; then
+  echo "❌ Error: ktlintFormat failed. Please fix the issues and try again."
+  exit 1
+
+else
+  echo "✅ Formatting successful. Adding changes to the commit..."
+  git add -u
+  exit 0
+fi
