Chore: Update build.gradle version code to 1.1.4, add GITHUB env check in release-package.ymlChore: Add GITHUB_TOKEN check to release workflow, clean up build.gradle and kotlin-common-conventions formatting

diff --git a/.github/workflows/release-package.yml b/.github/workflows/release-package.yml
--- a/.github/workflows/release-package.yml
+++ b/.github/workflows/release-package.yml
@@ -19,6 +19,18 @@ jobs:
           java-version: 22
       - name: Build with Gradle
         run: chmod +x ./gradlew
+      - name: Check GITHUB envs (safe)
+        run: |
+          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "GITHUB_TOKEN is missing"
+            exit 1
+          else
+            echo "GITHUB_TOKEN is set"
+          fi
+        env:
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Publish package
         run: gradle publish
         env:
